### ISSUE TITLE
Problem when fitting dataframe with only categorical features.

### ISSUE THREAD

**Issue by echatzikyriakidis** [avsolatorio/REaLTabFormer#6]
@avsolatorio Hi!

This line of code fails when fitting a dataframe that contains only Categorical features. Because no numerical or datetime features exists the list is empty and the `pd.concat` fails.

https://github.com/avsolatorio/REaLTabFormer/blob/311470accc400e4c7fae6fb2d8a7f9c3988b7b19/src/realtabformer/data_utils.py#L495

**Comment by avsolatorio** [comment]
@echatzikyriakidis good catch, thank you so much for reporting this! I have made the patch of the suggested change. I will deploy an updated release by end of the month. 😃
