### ISSUE TITLE
Can the model learn relationships of columns in long distance tables?

### ISSUE THREAD

**Issue by echatzikyriakidis** [avsolatorio/REaLTabFormer#9]
@avsolatorio Hi!

Assume the following 3 tables:

Table A
   Column A.1
   Column A.2
   Column A.3

Table B
   Column B.1
   Column B.2
   Column B.3

Table C
   Column C.1
   Column C.2
   Column C.3

In my example I skip the primary and foreign keys for simplicity.

The relationships are:

Table A [1..N] Table B
Table B [1..N] Table C

The parent Tabular model type can be used to model each table separately and the Relational model type can be used to model the above two relationships. The parent and child models will capture column relationships/correlations that exist inside each table or relationship. But what happens with correlations that exist in columns between Table A and Table C or any pair of columns from any pair of tables in the database? How someone can learn such relationships? Is it possible with RealTabFormer?

What if the Table A.Column A.1 is correlated with Table C.Column C.2? Each child model is conditioned only in the parent row and thus can learn dependencies only between directly connected tables.

What do you think? Is it possible to overcome this somehow?

**Comment by avsolatorio** [comment]
Hello @echatzikyriakidis, if I understand your use case correctly, you could implement a hierarchical data input.

If Table A is a non-relational table, you could use the standard tabular model to generate the synthetic data A'. Then, you can use the Seq2Seq model to fit Tables A and B to generate observations B'.

Then, assuming both values in A and B strongly correlate with observations in Table C, you could concatenate data from A and B and train a seq2seq model for C.

To generate synthetic samples, use the parent table model to generate A'. Then use the generated sample (A') on the first seq2seq model to generate B' observations. Concatenate A' and B' observations, and use these as input to the second seq2seq model to generate C'.

**Comment by limhasic** [comment]
in 

""" If Table A is a non-relational table, you could use the standard tabular model to generate the synthetic data A'. Then, you can use the Seq2Seq model to fit **Tables A and B** to generate observations B'. """

**Tables A and B** is Denormalized joined table?
